### PR TITLE
Initial 2018 files

### PR DESCRIPTION
**Pull request by KimDolleris**

### CODE REVIEW

**Comment by kwalrath** [comment]
Looks like the build failed because gulp wasn't found. Can you fix that, @KimDolleris?

**Comment by filiph** [comment]
I think Kim just added the sources and the generated files. I'll try to integrate those into the make pipeline. I haven't gotten the new site to work yet, though, so no promises.

**Comment by filiph** [comment]
Hey @KimDolleris, I'll need some input on this.

I expected that at least going to `src/2018/__dev` and manually running a script would build the site into `src/2018/dist`. But I can't even get the site to compile.

```
$ gulp build
[11:41:58] Using gulpfile ~/dev/site-events/src/2018/__dev/gulpfile.js
[11:41:58] Task 'build' is not in your gulpfile
[11:41:58] Please check the documentation for proper gulpfile formatting
```

I was going through the Novicell's README file but that didn't help — maybe I missed some important part.

At this point all I need is to be able to run a (combination of) script(s) and get the compiled site into some directory (ideally, `src/2018/dist`, to be consistent with what's in the repo). What's in `src/2018/dist` right now should ideally not be checked into CVS as it's a build output. Also, it would be better to have `index.html` _inside_ `dist` alongside the rest of the files, so I can serve from that directory (and not from `src/2018`, which includes all the sources).

For completeness, I'm on these versions of tools (should be latest in all instances):

```
$ npm -v
5.4.2
$ node -v
v6.10.3
$ gulp -v
[11:44:32] CLI version 3.9.1
```

**Comment by KimDolleris** [comment]
Hey guys - yeah its just the sourcefiles. The dist and the index should be ready to run. Sure thing with the index within the dist-folder. Lets do that.

**Comment by filiph** [comment]
I have this prepared over at https://github.com/filiph/site-events/tree/KimDolleris-master but I'm not merging it. Once I do, the site will go live at events.dartlang.org/2018/dartconf/. I'm delaying this because there is some discussion about the design.

cc @wmleler 

@KimDolleris, if you work further on this, I recommend pulling in the changes from  https://github.com/filiph/site-events/tree/KimDolleris-master first so we can merge easier.

**Pull request merged**
